name: Update campus events

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      
      - name: Generate data/events.json
        run: |
         echo "RUNNING fetch_events.py"
         ls -la
         ls -la script
         mkdir -p data
         python script/fetch_events.py
         python script/fetch_crier.py
         echo "AFTER RUN:"
         ls -la data


      - name: Commit events.json if changed
        run: |
         git add data/events.json data/crier.json
         git status --porcelain
         if git diff --cached --quiet; then
         echo "No changes."
         exit 0
         fi
         git config user.name "github-actions"
         git config user.email "github-actions@github.com"
         git commit -m "Update campus events"
         git push

